version: '3'

services:
  php:
    image: "thecodingmachine/php:7.4-v4-apache"
    volumes:
      - ./:/var/www/html/
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_MYSQLI: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_GD: 1
      APACHE_DOCUMENT_ROOT: "/var/www/html/public"
    ports:
      - 8000:80
      - 443:443

  nodejs:
    image: wiwatsrt/docker-laravel-nodejs
    volumes:
      - ./:/var/www

volumes:
  mysql: